"""
Tree index builder - converts DB hierarchy to PageIndex-inspired tree structure.

Zero LLM cost: Uses existing SQLAlchemy relationships for tree construction.
Optionally uses pre-generated chapter summaries for better LLM navigation.
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING, Dict, List, Optional
import json

from sqlalchemy.orm import joinedload

# Type checking imports (no runtime circular import)
if TYPE_CHECKING:
    from vn_legal_rag.offline.database_manager import LegalDocumentDB
    from vn_legal_rag.offline.models import (
        LegalDocumentModel,
        LegalChapterModel,
        LegalSectionModel,
        LegalArticleModel,
        LegalClauseModel,
        LegalPointModel,
    )

from vn_legal_rag.types import (
    TreeNode,
    TreeIndex,
    UnifiedForest,
    CrossRefEdge,
    NodeType,
)


class TreeIndexBuilder:
    """
    Build tree index from LegalDocumentDB with efficient eager loading.

    Zero LLM cost - tree structure extracted directly from DB relationships.
    Optionally uses pre-generated chapter summaries for better LLM navigation.
    """

    def __init__(
        self,
        db: LegalDocumentDB,
        chapter_summaries: Optional[Dict[str, str]] = None,
    ):
        """
        Initialize builder.

        Args:
            db: LegalDocumentDB instance
            chapter_summaries: Optional dict mapping chapter_id to description
                               (generated by ChapterSummaryGenerator)
        """
        self.db = db
        self.chapter_summaries = chapter_summaries or {}

    def build_document_tree(self, doc_id: str) -> Optional[TreeIndex]:
        """
        Build tree for single document with efficient single-query loading.

        Args:
            doc_id: Document ID (e.g., "59-2020-QH14")

        Returns:
            TreeIndex or None if document not found
        """
        # Lazy imports to avoid circular import
        from vn_legal_rag.offline.models import (
            LegalDocumentModel,
            LegalChapterModel,
            LegalSectionModel,
            LegalArticleModel,
            LegalClauseModel,
        )

        with self.db.SessionLocal() as session:
            # Load document with all relationships in single query
            doc = (
                session.query(LegalDocumentModel)
                .filter(LegalDocumentModel.id == doc_id)
                .options(
                    joinedload(LegalDocumentModel.chapters)
                    .joinedload(LegalChapterModel.sections)
                    .joinedload(LegalSectionModel.articles)
                    .joinedload(LegalArticleModel.clauses)
                    .joinedload(LegalClauseModel.points),
                    joinedload(LegalDocumentModel.chapters)
                    .joinedload(LegalChapterModel.articles)
                    .joinedload(LegalArticleModel.clauses)
                    .joinedload(LegalClauseModel.points),
                )
                .first()
            )

            if not doc:
                return None

            # Build tree from document
            root_node = self._build_document_node(doc)
            return TreeIndex(root=root_node, doc_id=doc_id)

    def build_forest(self, doc_ids: Optional[List[str]] = None) -> UnifiedForest:
        """
        Build unified forest from multiple documents.

        Args:
            doc_ids: List of document IDs (None = all documents)

        Returns:
            UnifiedForest with all trees and cross-references
        """
        # Lazy import to avoid circular import
        from vn_legal_rag.offline.models import LegalDocumentModel

        forest = UnifiedForest()

        with self.db.SessionLocal() as session:
            # Get document IDs
            if doc_ids is None:
                docs = session.query(LegalDocumentModel.id).all()
                doc_ids = [doc.id for doc in docs]

            # Build tree for each document
            for doc_id in doc_ids:
                tree = self.build_document_tree(doc_id)
                if tree:
                    forest.add_tree(tree)

            # Load cross-references
            cross_refs = self._load_cross_references(session, doc_ids)
            for edge in cross_refs:
                forest.add_cross_ref(edge)

        return forest

    def _build_document_node(self, doc: LegalDocumentModel) -> TreeNode:
        """Build document-level root node."""
        sub_nodes = []

        # Add chapters (ordered by position)
        for chapter in sorted(doc.chapters, key=lambda c: c.position):
            chapter_node = self._build_chapter_node(chapter)
            sub_nodes.append(chapter_node)

        return TreeNode(
            node_id=doc.id,
            node_type=NodeType.DOCUMENT,
            name=doc.title,
            description=f"{doc.loai_van_ban} số {doc.so_hieu}",
            content="",
            metadata={
                "so_hieu": doc.so_hieu,
                "loai_van_ban": doc.loai_van_ban,
                "co_quan_ban_hanh": doc.co_quan_ban_hanh,
                "ngay_ban_hanh": doc.ngay_ban_hanh.isoformat() if doc.ngay_ban_hanh else None,
                "tinh_trang": doc.tinh_trang,
            },
            sub_nodes=sub_nodes,
        )

    def _build_chapter_node(self, chapter: LegalChapterModel) -> TreeNode:
        """Build chapter node with sections and articles."""
        sub_nodes = []

        # Add sections (ordered by position)
        for section in sorted(chapter.sections, key=lambda s: s.position):
            section_node = self._build_section_node(section)
            sub_nodes.append(section_node)

        # Add direct articles (no section)
        for article in sorted(chapter.articles, key=lambda a: a.position):
            article_node = self._build_article_node(article)
            sub_nodes.append(article_node)

        # Use pre-generated description if available, otherwise compute article range
        description = self.chapter_summaries.get(chapter.id, "")
        if not description:
            # Fallback: compute article range
            all_article_nums = []
            for a in chapter.articles:
                all_article_nums.append(a.article_number)
            for section in chapter.sections:
                for a in section.articles:
                    all_article_nums.append(a.article_number)

            if all_article_nums:
                all_article_nums.sort(key=lambda x: int(x) if isinstance(x, str) and x.isdigit() else (x if isinstance(x, int) else 0))
                description = f"Điều {all_article_nums[0]}-{all_article_nums[-1]}"

        return TreeNode(
            node_id=chapter.id,
            node_type=NodeType.CHAPTER,
            name=chapter.title or f"Chương {chapter.chapter_number}",
            description=description,
            content=chapter.raw_text or "",
            metadata={
                "chapter_number": chapter.chapter_number,
                "position": chapter.position,
            },
            sub_nodes=sub_nodes,
        )

    def _build_section_node(self, section: LegalSectionModel) -> TreeNode:
        """Build section (mục) node with articles."""
        sub_nodes = []

        # Add articles (ordered by position)
        for article in sorted(section.articles, key=lambda a: a.position):
            article_node = self._build_article_node(article)
            sub_nodes.append(article_node)

        return TreeNode(
            node_id=section.id,
            node_type=NodeType.SECTION,
            name=section.title or f"Mục {section.section_number}",
            description="",
            content=section.raw_text or "",
            metadata={
                "section_number": section.section_number,
                "position": section.position,
            },
            sub_nodes=sub_nodes,
        )

    def _build_article_node(self, article: LegalArticleModel) -> TreeNode:
        """Build article (điều) node with clauses."""
        sub_nodes = []

        # Add clauses (ordered by position)
        for clause in sorted(article.clauses, key=lambda c: c.position):
            clause_node = self._build_clause_node(clause)
            sub_nodes.append(clause_node)

        return TreeNode(
            node_id=article.id,
            node_type=NodeType.ARTICLE,
            name=article.title or f"Điều {article.article_number}",
            description="",
            content=article.raw_text or "",
            metadata={
                "article_number": article.article_number,
                "position": article.position,
            },
            sub_nodes=sub_nodes,
        )

    def _build_clause_node(self, clause: LegalClauseModel) -> TreeNode:
        """Build clause (khoản) node with points."""
        sub_nodes = []

        # Add points (ordered by position)
        for point in sorted(clause.points, key=lambda p: p.position):
            point_node = self._build_point_node(point)
            sub_nodes.append(point_node)

        return TreeNode(
            node_id=clause.id,
            node_type=NodeType.CLAUSE,
            name=f"Khoản {clause.clause_number}",
            description="",
            content=clause.raw_text or "",
            metadata={
                "clause_number": clause.clause_number,
                "position": clause.position,
            },
            sub_nodes=sub_nodes,
        )

    def _build_point_node(self, point: LegalPointModel) -> TreeNode:
        """Build point (điểm) node - leaf level."""
        return TreeNode(
            node_id=point.id,
            node_type=NodeType.POINT,
            name=f"Điểm {point.point_letter}",
            description="",
            content=point.raw_text or "",
            metadata={
                "point_letter": point.point_letter,
                "position": point.position,
            },
            sub_nodes=[],  # Leaf node
        )

    def _load_cross_references(
        self, session, doc_ids: List[str]
    ) -> List[CrossRefEdge]:
        """
        Load cross-references for given documents.

        Args:
            session: SQLAlchemy session
            doc_ids: List of document IDs

        Returns:
            List of CrossRefEdge objects
        """
        # Lazy import to avoid circular import
        from vn_legal_rag.offline.models import LegalCrossReferenceModel

        edges = []

        # Query all cross-references with resolved targets
        cross_refs = (
            session.query(LegalCrossReferenceModel)
            .filter(
                LegalCrossReferenceModel.target_article_id.isnot(None),
                ~LegalCrossReferenceModel.target_article_id.startswith("ext"),
            )
            .all()
        )

        for ref in cross_refs:
            # Filter by doc_ids if specified
            source_doc = ref.source_article_id.split(":")[0] if ":" in ref.source_article_id else ""
            if doc_ids and source_doc not in doc_ids:
                continue

            edge = CrossRefEdge(
                source_node_id=ref.source_article_id,
                target_node_id=ref.target_article_id,
                reference_text=ref.reference_text or "",
                confidence=ref.confidence or 1.0,
            )
            edges.append(edge)

        return edges

    def export_to_json(self, forest: UnifiedForest, path: str):
        """
        Export forest to JSON file for caching.

        Args:
            forest: UnifiedForest to export
            path: Output file path
        """
        json_str = forest.to_json()
        Path(path).parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(json_str)

    def import_from_json(self, path: str) -> UnifiedForest:
        """
        Import forest from JSON file.

        Args:
            path: Input file path

        Returns:
            UnifiedForest loaded from JSON
        """
        with open(path, "r", encoding="utf-8") as f:
            json_str = f.read()
        return UnifiedForest.from_json(json_str)


__all__ = ["TreeIndexBuilder"]
